//go:build interop

// SPDX-License-Identifier: MIT

package interop

import (
	"context"
	"encoding/json"
	"net"
	"strconv"
	"sync"
	"testing"
	"time"

	modbus "github.com/otfabric/go-modbus"
)

// fixture is the simulated device the reference images are built with. The
// tests read it from the image under test, so expectations follow the image
// rather than a copy that could drift.
type fixture struct {
	Name             string         `json:"name"`
	UnitID           uint8          `json:"unitId"`
	Coils            *bitBlock      `json:"coils"`
	DiscreteInputs   *bitBlock      `json:"discreteInputs"`
	HoldingRegisters *registerBlock `json:"holdingRegisters"`
	InputRegisters   *registerBlock `json:"inputRegisters"`
	DeviceID         *struct {
		Objects []fixtureObject `json:"objects"`
	} `json:"deviceIdentification"`
}

type bitBlock struct {
	Address uint16 `json:"address"`
	Values  []bool `json:"values"`
}

type registerBlock struct {
	Address uint16   `json:"address"`
	Values  []uint16 `json:"values"`
}

type fixtureObject struct {
	ID    uint8  `json:"id"`
	Value string `json:"value"`
}

// objects returns the device identification objects of a category, in
// ascending id: 0..2 basic, 0..6 regular, all of them extended.
func (fx *fixture) objects(category modbus.DeviceIDCategory) []fixtureObject {
	var out []fixtureObject
	if fx.DeviceID == nil {
		return out
	}
	for _, o := range fx.DeviceID.Objects {
		switch {
		case o.ID <= 2,
			o.ID <= 6 && category >= modbus.DeviceIDRegular,
			o.ID >= 0x80 && category >= modbus.DeviceIDExtended:
			out = append(out, o)
		}
	}
	return out
}

// conformity is the conformity level FIXTURES.md prescribes: that of the
// highest category the fixture has objects for, without the bit for
// individual access.
func (fx *fixture) conformity() int {
	level := 1
	if fx.DeviceID == nil {
		return level
	}
	for _, o := range fx.DeviceID.Objects {
		switch {
		case o.ID >= 0x80:
			level = 3
		case o.ID >= 3 && level < 2:
			level = 2
		}
	}
	return level
}

var (
	fixtureMu   sync.Mutex
	fixtureDocs = map[string]*fixture{} // by image
)

// loadFixture returns the baseline fixture baked into the image of a.
func loadFixture(t testing.TB, a adapter) *fixture {
	t.Helper()
	fixtureMu.Lock()
	defer fixtureMu.Unlock()
	if fx, ok := fixtureDocs[a.image]; ok {
		return fx
	}
	out, stderr, err := docker("run", "--rm", a.image, "print-fixture", "baseline")
	if err != nil {
		t.Fatalf("print-fixture from %s: %v\n%s", a.image, err, stderr)
	}
	fx := &fixture{}
	if err := json.Unmarshal([]byte(out), fx); err != nil {
		t.Fatalf("fixture of %s is not JSON: %v", a.image, err)
	}
	if fx.Coils == nil || fx.DiscreteInputs == nil || fx.HoldingRegisters == nil || fx.InputRegisters == nil {
		t.Fatalf("fixture of %s lacks a table: the tests are written for the baseline fixture", a.image)
	}
	fixtureDocs[a.image] = fx
	return fx
}

// The rules the baseline fixture is generated by (FIXTURES.md § The baseline
// fixture), recomputed here so that a value read from a server is checked
// against something the image did not provide.

func baselineCoil(i int) bool          { return (i*7+3)%5 < 2 }
func baselineDiscreteInput(i int) bool { return (i*11+1)%3 == 0 }

func baselineHoldingRegister(i int) uint16 {
	first := []uint16{0, 1, 32767, 32768, 65535, 4660, 43981, 255}
	if i < len(first) {
		return first[i]
	}
	return uint16((i*257 + 13) % 65536)
}

func baselineInputRegister(i int) uint16 {
	first := []uint16{65535, 0, 32768, 1}
	if i < len(first) {
		return first[i]
	}
	return uint16((i*263 + 7) % 65536)
}

// device is a go-modbus server that serves a fixture by the rules of
// FIXTURES.md § Behaviour of the device, which every reference server
// follows. It is the device the reference clients are run against.
type device struct {
	Addr string // host:port the server listens on, all interfaces

	fx *fixture

	mu       sync.Mutex
	coils    []bool
	holding  []uint16
	requests []deviceRequest
}

// deviceRequest is one request as the handler saw it.
type deviceRequest struct {
	peer     string
	function modbus.FunctionCode
	unitID   uint8
}

// startDevice starts a go-modbus server that serves fx.
func startDevice(t testing.TB, fx *fixture) *device {
	t.Helper()
	d := &device{
		fx:      fx,
		coils:   append([]bool(nil), fx.Coils.Values...),
		holding: append([]uint16(nil), fx.HoldingRegisters.Values...),
	}
	// All interfaces: a container reaches the host through the bridge on
	// Linux, not through loopback.
	d.Addr = net.JoinHostPort("0.0.0.0", strconv.Itoa(freePort(t)))
	srv, err := modbus.NewServer(&modbus.ServerConfig{
		URL:        "tcp://" + d.Addr,
		Timeout:    60 * time.Second,
		MaxClients: 64,
		Logger:     newWireLog(t, "go-modbus server"),
	}, d)
	if err != nil {
		t.Fatalf("NewServer: %v", err)
	}
	if err := srv.Start(); err != nil {
		t.Fatalf("start go-modbus server on %s: %v", d.Addr, err)
	}
	t.Cleanup(func() { _ = srv.Stop() })
	return d
}

// seen records a request and reports whether it is for the device's unit.
// A request for any other unit identifier is answered with exception 11.
func (d *device) seen(peer string, fc modbus.FunctionCode, unitID uint8) error {
	d.mu.Lock()
	d.requests = append(d.requests, deviceRequest{peer, fc, unitID})
	d.mu.Unlock()
	if unitID != d.fx.UnitID {
		return modbus.ErrGWTargetFailedToRespond
	}
	return nil
}

// within reports whether addr..addr+quantity-1 lies in a block of n elements
// starting at base.
func within(base uint16, n int, addr, quantity uint16) bool {
	return addr >= base && int(addr)+int(quantity) <= int(base)+n
}

func (d *device) HandleCoils(_ context.Context, req *modbus.CoilsRequest) ([]bool, error) {
	if err := d.seen(req.ClientAddr, req.FunctionCode, req.UnitID); err != nil {
		return nil, err
	}
	d.mu.Lock()
	defer d.mu.Unlock()
	if !within(d.fx.Coils.Address, len(d.coils), req.Addr, req.Quantity) {
		return nil, modbus.ErrIllegalDataAddress
	}
	at := int(req.Addr - d.fx.Coils.Address)
	if req.IsWrite {
		copy(d.coils[at:], req.Args)
		return nil, nil
	}
	return append([]bool(nil), d.coils[at:at+int(req.Quantity)]...), nil
}

func (d *device) HandleDiscreteInputs(_ context.Context, req *modbus.DiscreteInputsRequest) ([]bool, error) {
	if err := d.seen(req.ClientAddr, req.FunctionCode, req.UnitID); err != nil {
		return nil, err
	}
	b := d.fx.DiscreteInputs
	if !within(b.Address, len(b.Values), req.Addr, req.Quantity) {
		return nil, modbus.ErrIllegalDataAddress
	}
	at := int(req.Addr - b.Address)
	return append([]bool(nil), b.Values[at:at+int(req.Quantity)]...), nil
}

func (d *device) HandleHoldingRegisters(_ context.Context, req *modbus.HoldingRegistersRequest) ([]uint16, error) {
	if err := d.seen(req.ClientAddr, req.FunctionCode, req.UnitID); err != nil {
		return nil, err
	}
	d.mu.Lock()
	defer d.mu.Unlock()
	if !within(d.fx.HoldingRegisters.Address, len(d.holding), req.Addr, req.Quantity) {
		return nil, modbus.ErrIllegalDataAddress
	}
	at := int(req.Addr - d.fx.HoldingRegisters.Address)
	if req.IsWrite {
		copy(d.holding[at:], req.Args)
		return nil, nil
	}
	return append([]uint16(nil), d.holding[at:at+int(req.Quantity)]...), nil
}

func (d *device) HandleInputRegisters(_ context.Context, req *modbus.InputRegistersRequest) ([]uint16, error) {
	if err := d.seen(req.ClientAddr, req.FunctionCode, req.UnitID); err != nil {
		return nil, err
	}
	b := d.fx.InputRegisters
	if !within(b.Address, len(b.Values), req.Addr, req.Quantity) {
		return nil, modbus.ErrIllegalDataAddress
	}
	at := int(req.Addr - b.Address)
	return append([]uint16(nil), b.Values[at:at+int(req.Quantity)]...), nil
}

// HandleMaskWrite sets the register to (current AND andMask) OR (orMask AND
// NOT andMask).
func (d *device) HandleMaskWrite(_ context.Context, req *modbus.MaskWriteRequest) error {
	if err := d.seen(req.ClientAddr, req.FunctionCode, req.UnitID); err != nil {
		return err
	}
	d.mu.Lock()
	defer d.mu.Unlock()
	if !within(d.fx.HoldingRegisters.Address, len(d.holding), req.Addr, 1) {
		return modbus.ErrIllegalDataAddress
	}
	at := int(req.Addr - d.fx.HoldingRegisters.Address)
	d.holding[at] = (d.holding[at] & req.AndMask) | (req.OrMask &^ req.AndMask)
	return nil
}

// HandleReadWriteRegisters checks both ranges before anything is written, and
// writes before it reads.
func (d *device) HandleReadWriteRegisters(_ context.Context, req *modbus.ReadWriteRegistersRequest) ([]uint16, error) {
	if err := d.seen(req.ClientAddr, req.FunctionCode, req.UnitID); err != nil {
		return nil, err
	}
	d.mu.Lock()
	defer d.mu.Unlock()
	base := d.fx.HoldingRegisters.Address
	if !within(base, len(d.holding), req.ReadAddr, req.ReadQty) ||
		!within(base, len(d.holding), req.WriteAddr, uint16(len(req.WriteValues))) {
		return nil, modbus.ErrIllegalDataAddress
	}
	copy(d.holding[req.WriteAddr-base:], req.WriteValues)
	at := int(req.ReadAddr - base)
	return append([]uint16(nil), d.holding[at:at+int(req.ReadQty)]...), nil
}

// HandleDeviceIdentification returns the objects of the fixture. The
// conformity level is left to the server, which derives it from the objects.
func (d *device) HandleDeviceIdentification(_ context.Context, req *modbus.DeviceIdentificationRequest) (*modbus.DeviceIdentificationResponse, error) {
	if err := d.seen(req.ClientAddr, req.FunctionCode, req.UnitID); err != nil {
		return nil, err
	}
	res := &modbus.DeviceIdentificationResponse{}
	if d.fx.DeviceID != nil {
		for _, o := range d.fx.DeviceID.Objects {
			res.Objects = append(res.Objects, modbus.DeviceIdentificationObject{ID: modbus.DeviceIDObjectID(o.ID), Value: o.Value})
		}
	}
	return res, nil
}

// coilsNow and holdingNow return the current state of the device.
func (d *device) coilsNow() []bool {
	d.mu.Lock()
	defer d.mu.Unlock()
	return append([]bool(nil), d.coils...)
}

func (d *device) holdingNow() []uint16 {
	d.mu.Lock()
	defer d.mu.Unlock()
	return append([]uint16(nil), d.holding...)
}

// takeRequests returns the requests the handler saw since the last call.
func (d *device) takeRequests() []deviceRequest {
	d.mu.Lock()
	defer d.mu.Unlock()
	out := d.requests
	d.requests = nil
	return out
}
